name: Sync to Gitee

on:
  push:
    branches: 
      - main  # 或您希望同步的分支

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Push to Gitee
      run: |
        git config --global user.name 'liukai'
        git config --global user.email '1298646637@qq.com'
        git remote add gitee https://gitee.com/lsuperkai/lk-proj-adminweb.git
        git push gitee HEAD:dev  # 将 main 分支推送到 Gitee
      env:
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
